# Variables
@baseUrl = http://localhost:3000/api/v1/users
@int = {{$randomInt 1000 9999}}
@authToken = {{login.response.body.data}}

### Get all users
GET {{baseUrl}}/ HTTP/1.1
Authorization: {{authToken}}

### Add a user
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "firstname": "{{int}}Member",
    "middlename": "Test",
    "lastname": "User",
    "email": "{{int}}@example.com",
    "password": "{{int}}",
    "joinDate": "2018-01-01",
    "phone": "+255755{{int}}00",
    "level": "member"
}


### Get user details
GET {{baseUrl}}/5f888c4cb19869774818060b
Authorization: {{authToken}}

 
### Update Specific User Details
PATCH {{baseUrl}}/5f885ee0943d0c74e49f5eb4 HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "firstname": "Updated",
    "middlename": "Initial",
    "lastname": " Admin",
    "email": "notadmin@example.com",
    "password": "NotAdmin",
    "joinDate": "2018-01-01",
    "phone": "0711404040",
    "level": "admin",
    "status": 1
}


### Delete a specific user
DELETE {{baseUrl}}/5f885ee0943d0c74e49f5eb4 HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}


### Post login credentials to get a token
 # @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}


### Add the first admin user with email admin@example.com and password admin
GET {{baseUrl}}/login HTTP/1.1
Authorization: {{authToken}}